[workspace]
name = "scikit-learn-benchmarks"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.12.*"
numpy = "*"
scipy = "*"
pandas = "<3"
ipykernel = "*"
tabulate = "*"
fastparquet = "*"
h5py = "*"
tqdm = "*"
psutil = "*"
requests = "*"
py-cpuinfo = "*"
matplotlib = "*"

[pypi-dependencies]
openml = ">=0.15.1"
dpctl = "*"
nvidia-ml-py = "*"

[feature.sklearn.dependencies]
scikit-learn = "1.9.*"

[feature.intel.dependencies]
scikit-learn = "*"
setuptools = "<82"

[feature.intel.pypi-dependencies]
array-api-compat = "*"
dpnp = "*"
scikit-learn-intelex-gpu = "*"

[feature.intel.activation.env]
SCIPY_ARRAY_API = "1"

[feature.sk-nvidia]
channels = ["conda-forge", "nvidia"]

[feature.sk-nvidia.system-requirements]
cuda = "12.9"

[feature.sk-nvidia.dependencies]
cuda-version = "12.9.*"
cupy = "*"

[feature.sk-nvidia.pypi-dependencies]
torch = { version = "*", index = "https://download.pytorch.org/whl/cu129" }
scikit-learn = { version = ">1.9", index = "https://pypi.anaconda.org/scientific-python-nightly-wheels/simple" }

[feature.sk-nvidia.activation.env]
SCIPY_ARRAY_API = "1"

[feature.sk-intel.pypi-dependencies]
dpnp = "*"
triton-xpu = { version = "==3.7.1", index = "https://download.pytorch.org/whl/xpu" }
torch = { version = ">=2.12.0", index = "https://download.pytorch.org/whl/xpu" }
scikit-learn = { version = ">1.9", index = "https://pypi.anaconda.org/scientific-python-nightly-wheels/simple" }

[feature.sk-intel.activation.env]
SCIPY_ARRAY_API = "1"

[feature.sklearn-cpu.pypi-dependencies]
array-api-compat = "*"
torch = { version = "*", index = "https://download.pytorch.org/whl/cpu" }
scikit-learn = { version = ">1.9", index = "https://pypi.anaconda.org/scientific-python-nightly-wheels/simple" }

[feature.sklearn-cpu.activation.env]
SCIPY_ARRAY_API = "1"

[environments]
sklearn = ["sklearn"]
sklearn-cpu = ["sklearn-cpu"]
sk-intel = ["sk-intel"]
sk-nvidia = ["sk-nvidia"]
intel = ["intel"]
