[workspace]
name = "scikit-learn-benchmarks"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.12.*"
numpy = "*"
scipy = "*"
pandas = "<3"
ipykernel = "*"
tabulate = "*"
fastparquet = "*"
h5py = "*"
tqdm = "*"
psutil = "*"
requests = "*"
py-cpuinfo = "*"
matplotlib = "*"
pydantic = "*"
pytest = "*"

[pypi-dependencies]
openml = ">=0.15.1"
dpctl = "*"
nvidia-ml-py = "*"
py-spy = "*"

[feature.sklearn.dependencies]
scikit-learn = "1.9.*"

[feature.sklearn-dev.dependencies]
cython = "*"
joblib = "*"
meson-python = "*"
ninja = "*"
pip = "*"
pkg-config = "*"
threadpoolctl = "*"
c-compiler = "*"
cxx-compiler = "*"

[feature.intel.dependencies]
scikit-learn = "1.8.*"
setuptools = "<82"

[feature.intel.pypi-dependencies]
array-api-compat = "*"
dpnp = "*"
scikit-learn-intelex-gpu = "*"

[feature.intel.activation.env]
SCIPY_ARRAY_API = "1"

[feature.skl-nvidia]
channels = ["conda-forge", "nvidia"]

[feature.skl-nvidia.system-requirements]
cuda = "12.9"

[feature.skl-nvidia.dependencies]
cuda-version = "12.9.*"
cupy = "*"

[feature.skl-nvidia.pypi-dependencies]
torch = { version = "*", index = "https://download.pytorch.org/whl/cu129" }

[feature.skl-nvidia.activation.env]
SCIPY_ARRAY_API = "1"

[feature.skl-intel.dependencies]
setuptools = "<82"

[feature.skl-intel.pypi-dependencies]
dpnp = "*"
triton-xpu = { version = "==3.7.1", index = "https://download.pytorch.org/whl/xpu" }
torch = { version = ">=2.12.0", index = "https://download.pytorch.org/whl/xpu" }

[feature.skl-intel.activation.env]
SCIPY_ARRAY_API = "1"

[feature.skl-cpu.pypi-dependencies]
array-api-compat = "*"
torch = { version = "*", index = "https://download.pytorch.org/whl/cpu" }

[feature.skl-cpu.activation.env]
SCIPY_ARRAY_API = "1"

[feature.reporting.dependencies]
scikit-learn = "1.9.*"
jupyter = "*"
matplotlib = "*"

[feature.reporting.pypi-dependencies]
Jinja2 = "*"

[environments]
sklearn = ["sklearn"]
sklearn-dev = ["sklearn-dev"]
skl-cpu = ["sklearn", "skl-cpu"]
skl-intel = ["sklearn", "skl-intel"]
skl-nvidia = ["sklearn", "skl-nvidia"]
intel = ["intel"]
reporting = ["reporting"]
